name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
    
    - uses: docker/setup-qemu-action@master
    - name: Set up QEMU
      with:
        platforms: all
        
    - uses: docker/login-action@v1
    - name: Login to Docker Hub
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - uses: docker/setup-buildx-action@v1
    - name: Set up Docker Buildx
    
    - uses: docker/build-push-action@v2
    - name: Build and push
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/refugiosos:latest
        
